Repository ispras/web-scraper-chrome-extension, pull requests merged in 2020-04, with the labels that each got.

#15 Added horizontal tables with complicated header
  .prettierrc
  package.json
  playgrounds/extension/tables.html
  playgrounds/extension/webpage.css
  src/devtools/views/SelectorEdit.html
  src/scripts/Controller.js
  src/scripts/Selector/SelectorTable.js
Labels: enhancement

#24 Json viewer
  package-lock.json
  package.json
  src/devtools/panel.css
  src/devtools/views/DataPreview.html
  src/devtools/views/ItemCard.html
  src/devtools/views/SitemapBrowseData.html
  src/scripts/Controller.js
  src/scripts/Selector.js
  yarn.lock
Labels: enhancement

#33 Model refactoring
  .babelrc
  package.json
  playgrounds/sitemap-tree/index.html
  src/background/background.js
  src/devtools/views/SitemapCreate.html
  src/devtools/views/SitemapEditMetadata.html
  src/scripts/Controller.js
  src/scripts/DataExtractor.js
  src/scripts/Model.js
  src/scripts/Scraper.js
  src/scripts/Selector.js
  src/scripts/Selector/SelectorTable.js
  src/scripts/Sitemap.js
  src/scripts/StoreDevtools.js
  src/scripts/StorePouchDB.js
  src/scripts/StoreRestApi.js
  tests/spec/ChromePopupBrowserSpec.js
  tests/spec/DataExtractSpec.js
  tests/spec/ScraperSpec.js
  tests/spec/SitemapSpec.js
  yarn.lock
Labels: refactoring

#32 Translations
  package.json
  src/_locales/en/messages.json
  src/_locales/ru/messages.json
  src/content_script/AttachedToolbar.html
  src/content_script/content_script.css
  src/devtools/views/DataPreview.html
  src/devtools/views/SelectorEdit.html
  src/devtools/views/SelectorList.html
  src/devtools/views/SelectorListItem.html
  src/devtools/views/SitemapCreate.html
  src/devtools/views/SitemapEditMetadata.html
  src/devtools/views/SitemapExport.html
  src/devtools/views/SitemapExportDataCSV.html
  src/devtools/views/SitemapImport.html
  src/devtools/views/SitemapList.html
  src/devtools/views/SitemapListItem.html
  src/devtools/views/SitemapScrapeConfig.html
  src/devtools/views/Viewport.html
  src/manifest.json
  src/options/options.html
  src/options/options.js
  src/popup/popup.html
  src/popup/popup.js
  src/scripts/ChromePopupBrowser.js
  src/scripts/Config.js
  src/scripts/ContentScript.js
  src/scripts/ContentSelector.js
  src/scripts/Controller.js
  src/scripts/Model.js
  src/scripts/Translator.js
  webpack.config.js
Labels: enhancement

#36 Refactored data extraction format, added export in JSON lines
  README.md
  docs/Scraping a site.md
  package.json
  src/_locales/en/messages.json
  src/_locales/ru/messages.json
  src/devtools/views/SitemapCreate.html
  src/devtools/views/SitemapExport.html
  src/devtools/views/SitemapExportData.html
  src/devtools/views/SitemapExportDataCSV.html
  src/devtools/views/SitemapImport.html
  src/devtools/views/SitemapListItem.html
  src/devtools/views/Viewport.html
  src/scripts/Controller.js
  src/scripts/DataExtractor.js
  src/scripts/Scraper.js
  src/scripts/Selector.js
  src/scripts/Selector/ConstantValue.js
  src/scripts/Selector/SelectorDocument.js
  src/scripts/Selector/SelectorElement.js
  src/scripts/Selector/SelectorElementAttribute.js
  src/scripts/Selector/SelectorElementClick.js
  src/scripts/Selector/SelectorElementScroll.js
  src/scripts/Selector/SelectorElementStyle.js
  src/scripts/Selector/SelectorGroup.js
  src/scripts/Selector/SelectorHTML.js
  src/scripts/Selector/SelectorImage.js
  src/scripts/Selector/SelectorInputValue.js
  src/scripts/Selector/SelectorLink.js
  src/scripts/Selector/SelectorPopupLink.js
  src/scripts/Selector/SelectorTable.js
  src/scripts/Selector/SelectorText.js
  src/scripts/Sitemap.js
  src/scripts/StorePouchDB.js
  yarn.lock
Labels: enhancement, refactoring

#37 Updated documentation
  README.md
  docs/Installation.md
  docs/Open Web Scraper.md
  docs/Selectors.md
  docs/Selectors/Constant value.md
  docs/Selectors/Document selector .md
  docs/Selectors/Element click selector.md
  docs/Selectors/Element scroll down selector.md
  docs/Selectors/Element selector.md
  docs/Selectors/Element style selector.md
  docs/Selectors/Grouped selector.md
  docs/Selectors/HTML selector.md
  docs/Selectors/Image selector.md
  docs/Selectors/Input value.md
  docs/Selectors/Link popup selector.md
  docs/Selectors/Link selector.md
  docs/Selectors/Text selector.md
  docs/Storage backends.md
  docs/images/installation/Firefox_scraper_1.png
  docs/images/installation/Firefox_scraper_2.png
  docs/images/installation/Firefox_scraper_3.png
  docs/images/installation/Firefox_scraper_4.png
  docs/images/installation/chrome_scraper_1.png
Labels: documentation
